### ISSUE TITLE
Unexpected format for 'id' command

### ISSUE THREAD

**Issue by quizilkend** [nrdvana/makerware-docker#1]
When I run makerware-docker, I get the following error:

> Unexpected format for 'id' command : uid=1000(samuel) gid=1000(samuel) Gruppen=1000(samuel),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),101(systemd-journal),105(input),109(netdev),112(bluetooth),117(lpadmin),118(scanner),130(davfs2) at /bin/run-conveyor-and-makerware line 9.

I don't really get what's wrong. Can you help me?

**Comment by nrdvana** [comment]
I think it was the internationalization of "groups=".  Can you pull latest and try again?

**Comment by nrdvana** [comment]
To answer the broader question, `makerware-docker` runs `/usr/bin/id` outside of the container then sends that info to `docker/run-conveyor-and-makerware` inside the container so that it can create a matching user for you inside the container.

**Comment by quizilkend** [comment]
Thank you. That helped. Although it is not starting makerware, but I will open a separate issue for that.
